name: CI-Linux

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
    services:
      trextestdb:
        image: sourcepole/trextestdb
        ports:
          - 5432:5432

    name: ${{ matrix.version }} - x86_64-unknown-linux-gnu
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup test DB
        run: |
          docker ps -a
          psql -U t_rex -h 127.0.0.1 t_rex_tests -f geozero/tests/data/postgis.sql
        env:
          PGPASSWORD: t_rex

      - name: install dependencies
        run: |
          sudo apt-get install -y libgdal-dev libgeos-dev

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-x86_64-unknown-linux-gnu
          profile: minimal
          override: true

      - name: check build
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --all-features --bins --examples --tests --benches

      - name: tests
        run: |
          cargo test --workspace --all-features
          cargo test --workspace --all-features -- --ignored postgis
          cargo test --manifest-path geozero/Cargo.toml
          cargo test --manifest-path geozero/Cargo.toml --no-default-features
        env:
          #DATABASE_URL: postgresql://ci:ci@localhost/postgistest?sslmode=disable"
          DATABASE_URL: postgresql://t_rex:t_rex@127.0.0.1/t_rex_tests?sslmode=disable"
